### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by samtrippy** [eecs394-s16/PitchEvaluator#5]

**Comment by ybpinto** [comment]
Write out some user stories about this

**Comment by samtrippy** [comment]
**Judge User Stories**
- As a judge, I want to quickly begin the review process
- As a judge, I want to be able to go back and edit my reviews

**Professor User Stories**
- As a professor, I want to be able to filter reviews/comments by judge
- As a professor, I want to be able to filter reviews/comments by team
- As a professor, I want to see valuable aggregate data from completed reviews
- As a professor, I want to show teams their scores

**Team User Stories**
- As a student, I want to see my team's scores and comments
